### ISSUE TITLE
Log to file

### ISSUE THREAD

**Issue by brondum** [Olling/slog#1]
Make the logger able to use file output.
for both persistent logging and the ability for log tools to gather the logs.

Thank you in advance
/Peter

**Comment by Olling** [comment]
Hi Peter,

You can set the output for a single logger like this:
```
f, _ := os.Create("/tmp/infolog")
defer f.Close()
slog.InfoLogger.SetOutput(f)
slog.PrintInfo("Info to disk")
```

Or for all loggers:
```
f, _ := os.Create("/tmp/log")
defer f.Close()
slog.SetOutput(f)
slog.PrintInfo("Log to disk")
```

/Olling
